#!/bin/bash

logger "shdns $$ Started listening"
/home/mikal/opensource-unstable/shdns/shdns /tmp/shdns-$$ &
cat - > /tmp/shdns-$$
logger "shdns $$ Waiting for processor to end"
wait
logger "shdns $$ Stopped listening"