...\" $Header: /usr/local/google/home/mikal/cvs/pandascript/man/pandascript.1,v 1.1 2000-12-26 09:35:35 mikal Exp $
...\"
...\"	transcript compatibility for postscript use.
...\"
...\"	synopsis:  .P! <file.ps>
...\"
.de P!
\\&.
.fl			\" force out current output buffer
\\!%PB
\\!/showpage{}def
...\" the following is from Ken Flowers -- it prevents dictionary overflows
\\!/tempdict 200 dict def tempdict begin
.fl			\" prolog
.sy cat \\$1\" bring in postscript file
...\" the following line matches the tempdict above
\\!end % tempdict %
\\!PE
\\!.
.sp \\$2u	\" move below the image
..
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "pandascript" "1"
.SH "NAME"
pandascript \(em a scriptable front end to the Panda PDF generation API
.SH "SYNOPSIS"
.PP
.nf
\fBpandascript\fP
  
.fi
.SH "DESCRIPTION"
.PP
\fBpandascript\fP is an optional scriptable front end to the Panda PDF generation API\&.
    
.SH "COMMANDS"
.PP
\fBpandascript\fP recognizes these commands when they appear on standard input:
.IP "output" 10
Defines the name of the PDF document that you would like to create as the output of \fBpandascript\fP\&. There is currently no way of specifying standard output as the output location\&.
.RS
.IP "filename" 10
Quoted string\&. The name of the PDF file to be created\&.
.RE
.IP "close" 10
Close the document named in the output command\&. This includes writing out all of the PDF information that has been created during the session\&.
.IP "newpage" 10
Create a newpage in the PDF document\&. Only on page may be editted at a time, and there is no way to go backwards in the pages of the PDF, so be sure that you have finished creating the current page before issuing this command\&.
.IP "imagebox" 10
The equivalent of the imagebox(3) function call from the Panda API\&. The following arguements are required:

.RS
.IP "top" 10
Integer\&. The location of the top of the image\&.
.IP "left" 10
Integer\&. The location of the left hand side of the image\&.
.IP "bottom" 10
Integer\&. The location of the bottom of the image\&.
.IP "right" 10
Integer\&. The location of the right hand side of the image\&.
.IP "filename" 10
Quoted string\&. The name of the image file that is being inserted into the PDF file\&.
.IP "type" 10
The type of the image that is being inserted\&. One of: TIFFIMG or JPEGIMG\&.
.RE
.IP "imageboxrot" 10
The equivalent of the imageboxrot(3) function call from the Panda API\&. This is very similar to the imagebox command above, but allows for the image to be rotated on the page\&. The following arguements are required:

.RS
.IP "top" 10
Integer\&. The location of the top of the image\&.
.IP "left" 10
Integer\&. The location of the left hand side of the image\&.
.IP "bottom" 10
Integer\&. The location of the bottom of the image\&.
.IP "right" 10
Integer\&. The location of the right hand side of the image\&.
.IP "angle" 10
Floating point\&. The angle the image should be rotated at\&.
.IP "filename" 10
Quoted string\&. The name of the image file that is being inserted into the PDF file\&.
.IP "type" 10
The type of the image that is being inserted\&. One of: TIFFIMG or JPEGIMG\&.
.RE
.IP "textbox" 10
The equivalent of the textbox(3) function call from the Panda API\&. This inserts a text string onto the current page in the PDF document\&. The following arguements are required:

.RS
.IP "top" 10
Integer\&. The location of the top of the textbox\&.
.IP "left" 10
Integer\&. The location of the left hand side of the textbox\&.
.IP "bottom" 10
Integer\&. The location of the bottom of the textbox\&.
.IP "right" 10
Integer\&. The location of the right hand side of the textbox\&.
.IP "text" 10
Quoted string\&. The text to insert\&.
.RE

.RS
.IP "setfontmode" 10
Integer\&.
.IP "setcharspacing" 10
Float\&.
.IP "setwordspacing" 10
Float\&.
.IP "sethorizscaling" 10
Float\&.
.IP "setleading" 10
Float\&.
.IP "setfont" 10
Quoted string\&.
.RE
.SH "DATA TYPES"
.PP
The following data types are defined for \fBpandascript\fP:
.IP "Quoted string" 10
This is any text, wrapped in quote characters\&. For example "frog" "the quick brown duck" and "wasabe is yummy"\&.
.IP "Integer" 10
A number without a decimal point\&. For example 1, 42, or -461\&.
.IP "Float" 10
A number with a decimal point\&. Examples include: 1\&.4; 46\&.56; or -978\&.6\&.
.SH "EXAMPLE"
.PP
There is sample code generated by demo\&.sh as part of the \fBpandascript\fP distribution\&.
.SH "AUTHOR"
.PP
Panda and \fBpandascript\fP are under development by Michael Still (mikal@stillhq\&.com)\&. All code is Copyright Michael Still 2000,  and is released under the GPL\&. Code submissions are welcomed\&. Contact Michael at the address above if you have something you would like to contribute\&.
.SH "BUGS"
.PP
There  are no known bugs in Panda or \fBpandascript\fP\&. If you find one, please contact mikal@stillhq\&.com and let me know\&.
.SH "VERSION"
.PP
This information was last updated for version 0\&.3 of \fBpandascript\fP\&.
    
...\" created by instant / docbook-to-man, Tue 26 Dec 2000, 20:27
