all: connected disconnected connexec disconnexec shdnsexec

connected: connected.c
	gcc connected.c -o connected

disconnected: disconnected.c
	gcc disconnected.c -o disconnected

connexec: connexec.c
	gcc connexec.c -o connexec

disconnexec: disconnexec.c
	gcc disconnexec.c -o disconnexec

shdnsexec: shdnsexec.c
	gcc shdnsexec.c -o shdnsexec