#!/usr/bin/perl

# This script is used to add news items to a given page -- it is assumed that
# this script is run in an htaccess protected area

# Please don't laugh at my perl, this was all developed as a perl learning
# exercise.

use strict;
use CGI;

# Setup the result of the CGI
my($result, $path, $newsname, $newsline, $highest, $temp, $OUTPUT, @crosspost);
$result = new CGI();

# The path is where to find the information to build the pages
$path = "/home/httpd/html/";

# Output the standard HTML prelude, which includes stuff like the page title
print $result->header;

# Get the extra arguements
$newsname = $result->param('newsitem');
@crosspost = $result->param('crosspost');

if($newsname eq ""){
  error("$path", "No news area name specified for modification.");
  exit;
}

dumpfile("$path/common/stdnews-start");
print "News item committed to $newsname @crosspost";
dumpfile("$path/common/stdnews-divider");

commitnewsitem($newsname);

foreach(@crosspost){
  commitnewsitem($_);
}

print $result->end_html;

exit;








sub commitnewsitem{
  my($newsname) = @_;

  # Prepare to do the actual committal
  $highest=`ls $path/news/$newsname | egrep -v "^9.*" | sort -r | head -1`;
  $highest=$highest + 1;
  $highest=sprintf("%06d", $highest);
  
  print "The news item is being committed, with it's news id being $highest";
  print "</b><BR><BR>\n";
  
  # Actually commit
  open OUTPUT, "> $path/news/$newsname/$highest" or die "Cannot open";

  $temp = $result->param('title');
  print OUTPUT "TITLE: $temp\n";
  
  $temp = $result->param('postdate');
  print OUTPUT "POSTDATE: $temp\n";
  
  $temp = $result->param('postemail');
  print OUTPUT "POSTER: $temp\n";

  $temp = $result->param('poster');
  print OUTPUT "POSTERNAME: $temp\nBEGIN CONTENT\n";
  
  $temp = $result->param('content');
  $temp =~ s/\'\'/\"/g;
  print OUTPUT "$temp";
  
  close OUTPUT;
  
  print "Done writing to $path/news/$newsname/$highest";
  dumpfile("$path/common/stdnews-end");
}

# Dump the named file to stdout
sub dumpfile{
  my($file) = @_;
  my($FILEBIT);

  print "\n<! $file >\n";
  open FILEBIT, $file;

  while(<FILEBIT>){
    print "$_";
    }

  print "\n";
  close(FILEBIT);
  }

# Display an error message to the user
sub error{
  my($path, $message) = @_;

  dumpfile("$path/common/stdnews-start");
  print "Error!";
  dumpfile("$path/common/stdnews-divider");
  print "$message\n";
  print "</b><BR><BR>\n";
  print "Please contact <a href=\"mailto:mikal\@stillhq.com\">mikal\@stillhq.com </a> and let him know the URL you were trying to access (normally at the top of the page), and what link you clicked on to get here (if there was one).\n";
  dumpfile("$path/common/stdnews-end");
  print $result->end_html;
}
