#!/usr/bin/perl

use strict;
my($cmd, $cmdstr, $input, $output, $arg, $TMP, $suppress);

# Make sure local scripts can run
$ENV{PATH} = $ENV{PATH} . ":.";
$suppress = 0;

# This script runs through the specified docbook source, and applies the 
# commands in <execute></execute> blocks. It also plays games with conditional
# inclusion of text...
#
# <execute><cmd></cmd><args></args><input></input><output></output></execute>
# <postexecute>... as above ...</postexecute>
#
# execute blocks happen as the file is read (including recursively)
# postexecute blocks happen once the entire file has been processed, and have 
# default input of the processed file

# This should be fixed...
open TMP, "> builddb-$$.tmp";
process("execute", "", \*STDIN, \*TMP);
close TMP;
open TMP, "< builddb-$$.tmp";
process("postexecute", "builddb-$$.tmp", \*TMP, \*STDOUT);
close TMP;
unlink "builddb-$$.tmp";
exit;

sub process($){
    my($exblock, $exfilename, $INPTR, $OUTPTR) = @_;

    while(<$INPTR>){
	if((/(.*)<\/slidetext>/) || (/(.*)<\/noslide>/)){
	    $suppress = 0;
	}
	elsif((/(.*)<slidetext>/) && ($ARGV[0] ne "jpg")){
	    $suppress = 1;
	}
	elsif((/(.*)<slidebreak>/) && ($ARGV[0] ne "jpg")){
	}
	elsif(/(.*)<noslide>/){
	    if($ARGV[0] eq "jpg"){
		$suppress = 1;
	    }
	}
	elsif(/(.*)<slideinclude>/){
	}
	elsif(/(.*)<\/slideinclude>/){
	}
	elsif((/(.*)<$exblock>(.*)<\/$exblock>(.*)/) && ($suppress == 0)){
	    print $OUTPTR $1;
	    $cmd = $2;

	    $_ = $cmd;
	    if(/<input>/){
		$input = $cmd;
		$input =~ s/.*<input>//;
		$input =~ s/<\/input>.*//;
	    }
	    else{
		$input = "";
	    }

	    if(/<output>/){
		$output = $cmd;
		$output =~ s/.*<output>//;
		$output =~ s/<\/output>.*//;
	    }
	    else{
		$output = "";
	    }

	    if(/<args>/){
		$arg = $cmd;
		$arg =~ s/.*<args>//;
		$arg =~ s/<\/args>.*//;
	    }
	    else{
		$arg = "";
	    }

	    $cmd =~ s/.*<cmd>//;
	    $cmd =~ s/<\/cmd>.*//;

	    if(($cmd ne "todo") && ($cmd ne "nextedition")
	      && ($cmd ne "cat")){
		if($arg ne ""){
		    $cmdstr = "$cmd $arg $ARGV[0]";
		}
		else{
		    $cmdstr = "$cmd $ARGV[0]";
		}

		if($input ne ""){
		    if($exblock ne "postexecute"){
			$cmdstr = "$cmdstr $input < $input";
		    }
		    else{
			$cmdstr = "$cmdstr < $input";
		    }
		}
		elsif($exblock eq "postexecute"){
		    $cmdstr = "$cmdstr < $exfilename";
		}
		
		
		if($output ne ""){
		    $cmdstr = "$cmdstr > $output";
		}
		
		print STDERR "Executing: $cmdstr\n";
		$output=`$cmdstr`;
		$output =~ s/([^\r])\n/$1\r\n/g;
		print $OUTPTR "$output";
	    }
	    elsif($cmd eq "todo"){
		print $OUTPTR "<figure>\n";
		print $OUTPTR "<title>$input</title>\n";
		print $OUTPTR `img todo.png eps`;
		print $OUTPTR "</figure>\n";
	    }
	    elsif($cmd eq "nextedition"){
	    }
	    elsif($cmd eq "cat"){
	      $output=`cat $input`;
	      print $OUTPTR "$output";
	    }

	    print $OUTPTR "$3";
	}
	elsif($suppress == 0){
	    print $OUTPTR $_;
	}
    }
}
