#!/usr/bin/perl

# Arguements (all optional):
#   - The section number to wrap the code in
#   - The name of the source file

use strict;
my($suppress);

$suppress = 0;

print STDERR "code2db: $ARGV[0] $ARGV[1] $ARGV[2]\n";

# Make C code safe for display in docbook
if($ARGV[1] ne ""){
    print "<sect$ARGV[0]><title>Code: $ARGV[1]</title>\n";
}
print "<programlisting>\n";

while(<STDIN>){
    chomp;
    if(/^[ \t]*\/\*\*\*\*\*\*\*\*\*/){
	$suppress = 1;
    }
    elsif($suppress == 0){
	s/\r$//;
	
	s/&/&amp;/g;
	s/</&lt;/g;
	s/>/&gt;/g;
	
	print "$_\r\n";
    }

    if(($suppress == 1) && (/\*\*\*\*\*\*\*\*\*\/$/)){
	$suppress = 0;
    }
}

print "</programlisting>\n";

if($ARGV[1] ne ""){
    print "</sect$ARGV[0]>\n";
}
else{
    print "<para><emphasis>Code: $ARGV[0]</emphasis></para>\n";
}
