#!/usr/bin/perl

use strict;
my($suppress);

$suppress = 0;

# Make C code safe for display in docbook
if($ARGV[2] ne ""){
    print "<sect$ARGV[0]><title>Code: $ARGV[1]</title>\n";
}
print "<programlisting>\n";

while(<STDIN>){
    chomp;
    if(/^[ \t]*\/\*\*\*\*\*\*\*\*\*/){
	$suppress = 1;
    }
    elsif($suppress == 0){
	s/\r$//;
	
	s/&/&amp;/g;
	s/</&lt;/g;
	s/>/&gt;/g;
	
	print "$_\r\n";
    }

    if(($suppress == 1) && (/\*\*\*\*\*\*\*\*\*\/$/)){
	$suppress = 0;
    }
}

print "</programlisting>\n";

if($ARGV[2] ne ""){
    print "</sect$ARGV[0]>\n";
}
else{
    print "<para><emphasis>Code: $ARGV[0]</emphasis></para>\n";
}
