#!/usr/bin/perl

# 0: Filename
# 1: Format

use strict;
my($filename, $id, $x, $y, $size, $divisor);

print STDERR "Img args: $ARGV[0] $ARGV[1]\n";
$filename = "gen-".$ARGV[0];
$filename =~ s/.[a-zA-Z]+$/.$ARGV[1]/;

# Determine the current size of the image
$id=`identify $ARGV[0] | tr -s " " | cut -f 3 -d " "`;
$_ = $id;
/([0-9]+)x([0-9]+)+.*/;
$x = $1;
$y = $2;
print STDERR "Image id: $id\n";
print STDERR "Dimensions: $x, $y\n";

$divisor = 1;
while($x > 320){
  $x /= 2;
  $divisor *= 2;
}
$y /= $divisor;
print STDERR "New dimensions: $x, $y\n";

print STDERR "Converting $ARGV[0] -> $filename\n";
$size = "$x"."x"."$y";
print STDERR "Executing convert -sample $size $ARGV[0] $filename\n";
`convert -sample $size $ARGV[0] $filename`;
print "<graphic format=\"$ARGV[1]\" fileref=\"$filename\">\n";
