#!/bin/bash

rm -f insertall-$$.tmp 2> /dev/null

for item in `ls | egrep $1 | egrep -v "~$"`
do
  echo "<execute><cmd>builddb</cmd><args>$2</args><input>$item</input></execute>" >> insertall-$$.tmp
done

builddb < insertall-$$.tmp
rm insertall-$$.tmp
