#!/usr/bin/perl

# $ARGV[0] is the command to execute
# $ARGV[1] is the directory to look in
# $ARGV[2] is the regular expression to search by
# $ARGV[3] is the arguements to the command

use strict;
my($LIST, $commands);

$commands = "";
print STDERR "insertall: Searching $ARGV[1] for $ARGV[2]\n";
open (LIST, "ls $ARGV[1] |");
while(<LIST>){
    chomp;
    print STDERR "insertall: Found $_\n";
    if(/$ARGV[2]/){
	    $commands = $commands."<execute><cmd>$ARGV[0]</cmd><args>$ARGV[3]</args><input>$ARGV[1]/$_</input></execute>\n";
	    print STDERR "insertall: Including\n";
	}
}

print `echo "$commands" | builddb`; 
