#!/usr/bin/perl

# Make a text file have a maximum line width. Arguements are:
#   - max width
#   - indent on broken line

# todo: doesn't deal with tabs, or broken line indent, or forced newlines...

use strict;
my($word, $indent);

$indent = 0;
while(<STDIN>){
    chomp;
    
    foreach $word (split(/ /, $_)){
	if(($indent + length($word)) > $ARGV[0]){
	    print "\r\n";
	    $indent = 0;
	}
	
	$indent += length($word);
	print "$word ";
    }
}
