#!/usr/local/bin/perl

use strict;

my($chapname, $chaptitle, $slidename, $slidetitle, $incmode, $suppress,
   $LIST, $SLIDE, $tablerowcount);

$incmode = 0;
$suppress = 0;
$chapname = "";

open LIST, "> slides-list";

# Eat the input and turn it into slides for a presentation
while(<STDIN>){
    # Be keen to turn include mode off, and slow to turn it on...
    if(/(.*)<\/slideinclude>/ || /(.*)<\/slidetext>/){
	if($chapname ne ""){
	    $_ = makeslidetext($1);
	    print SLIDE "$_\n";
	}
	
	$incmode = 0;
	print STDERR "Turning include mode off\n";
    }
    if(($incmode == 1) && ($chapname ne "")){
	$_ = makeslidetext($_);
	print SLIDE "$_";
    }
    elsif($incmode == 1){
	print STDERR "Included text skipped for lack of a slide: $_";
    }

    # Found a chapter
    if(/.*<chapter .*>/i){
	$chapname = "";
    }

    # Found a slide name (a title)
    if((/(.*)<title>(.*)<\/title>.*/i) && ($suppress == 0)){
	if($1 eq "<figure>"){
	}
	elsif($chapname eq ""){
	    $chaptitle = $2;
	    $chapname = makefile($2);
	    
	    close SLIDE;
	    open SLIDE, "> content/$chapname";
	    print SLIDE "TITLE: $chaptitle\n\n";
	    print LIST "content/$chapname\n";
	    print STDERR "New slide: $chaptitle at content/$chapname\n";
	}
	else{
	    $slidetitle = $2;
	    $slidename = makefile($2);
	    $slidename =~ s/^$chapname-//;
	    
	    close SLIDE;
	    open SLIDE, "> content/$chapname-$slidename";
	    print SLIDE "TITLE: $chaptitle -- $slidetitle\n\n";
	    print LIST "content/$chapname-$slidename\n";
	    print STDERR "New slide: $chaptitle -- $slidetitle at content/$chapname-$slidename\n";
	}
    }
    
    if(/.*<slideinclude>/ || /.*<slidetext>/){
	$incmode = 1;
	print STDERR "Turning include mode on\n";
    }

    # Forcing a page break in a side
    if(/.*<slidebreak>/){
	print STDERR "Slide page break\n";
	$_ = $slidename;
	close SLIDE;

	if(/(.*-cont-)([0-9]+)/){
	    $slidename = "$1".($2 + 1);
	}
	else{
	    my($hyphen);
	    if($slidename ne ""){
		$hyphen = "-";
	    }
	    else{
		$hyphen = "";
	    }

	    $slidename = "$slidename$hyphen"."cont-2";
	}

	print STDERR "New slide name is $slidename\n";
	open SLIDE, "> content/$chapname-$slidename";
	print SLIDE "TITLE: $chaptitle -- $slidetitle (continued)\n\n";
	print LIST "content/$chapname-$slidename\n";
    }

    # We can also suppress titles from being included
    if(/.*<noslide>/){
	$suppress = 1;
	print STDERR "Suppressing contents of sgml\n";
    }
    if(/.*<\/noslide>/){
	$suppress = 0;
	print STDERR "Suppression disabled\n";
    }
}

exit;

sub makefile(){
    my($temp) = @_;

    $temp = lc($temp);
    $temp =~ s/[ \t]/-/g;
    $temp =~ s/://g;
    $temp =~ s/the-//g;
    $temp =~ s/\?//g;
    $temp =~ s/'//g;
    return $temp;
}

sub makeslidetext(){
    my($temp) = @_;
    my($linelen);

    # Convert tables to HTML
    $linelen = -42;
    
    $_ = $temp;
    if(/.*<row>/){
	if($tablerowcount == 1){
	    $temp =~ s/<row>/<tr bgcolor=BBBBBB>/;
	    $tablerowcount = 0;
	}
	else{
	    $temp =~ s/<row>/<tr>/;
	    $tablerowcount = 1;
	}
    }

    $temp =~ s/<\/row>/<\/tr>/g;

    $temp =~ s/<entry>/<td>/g;
    $temp =~ s/<\/entry>/<\/td>/g;
    $temp =~ s/<thead>//g;
    $temp =~ s/<\/thead>//g;
    $temp =~ s/<tbody>//g;
    $temp =~ s/<\/tbody>//g;
    $temp =~ s/<tgroup[^>]*>//g;
    $temp =~ s/<\/tgroup>//g;
#    $temp =~ s/<table[^>]*><title>(.*)<\/title>/<title>$1<\/title><br><table>/g;
    $_ = $temp;
    if(/.*<table>/){
	$tablerowcount = 1;
    }
    $temp =~ s/<table[^>]*><title>(.*)<\/title>/<table>/g;

    # Deal with quotes
    $temp =~ s/<quote>/<i>/g;
    $temp =~ s/<\/quote>/<\/i>/g;

    # Deal with images
    $temp =~ s/<figure>/<br><br><div align=\"center\">/g;
    $temp =~ s/<title>/<b>/g;
    $temp =~ s/<\/title>/<\/b>/g;
    $temp =~ s/<graphic format.*fileref=\"/<br><img src=\"\/notes\/presentations\/content\//g;
    $temp =~ s/<\/figure>/<\/div><BR><BR>/g;

    # Footnotes
    $temp =~ s/<footnote><para>/<i>(/g;
    $temp =~ s/<\/para><\/footnote>/)<\/i>/g;

    # Listitems
    $temp =~ s/<orderedlist>//g;
    $temp =~ s/<\/orderedlist>//g;
    $temp =~ s/<itemizedlist>//g;
    $temp =~ s/<\/itemizedlist>//g;
    $temp =~ s/<listitem><para>/<li>/g;
    $temp =~ s/<\/para><\/listitem>//g;

    # Source code
    $temp =~ s/<programlisting>/<pre>/g;
    $temp =~ s/<\/programlisting>/<\/pre>/g;

    # Emphasis / command
    $temp =~ s/<emphasis>/<i>/g;
    $temp =~ s/<\/emphasis>/<\/i>/g;
    $temp =~ s/<command>/<i><b>/g;
    $temp =~ s/<\/command>/<\/b><\/i>/g;

    # Sections
    $temp =~ s/<sect[^>]*>/<BR><BR>/g;
    $temp =~ s/<\/sect[^>]*>//g;

    # Other stuff
    $temp =~ s/<slidetext>//g;
    $temp =~ s/<\/slidetext>//g;
    $temp =~ s/<para>/<BR><BR>/g;
    $temp =~ s/<\/para>//g;

    return $temp;
}
