#!/usr/bin/perl

use strict;
my($HISTORY, $filename, $date, %dateline, $day, $adate,
   $author, %cols, $newcolnum, @today, @html, $event, $file, $user, $i,
   $table, %authorcolor, @colors, $newauthnum, %heading, $color, $temp,
   $revision, $lines, $state, %authorcommits, $nowmonth, $prevmonth, $prevyear,
   @monthnames, $headerhtml, $loghtml, $nowyear, $comment, $OUTPUT, $INDEX);

open HISTORY, "< logout";

# We need some colors for authors -- I only bother to define 10 here
$colors[0] = "FF9900";
$colors[1] = "FFFF00";
$colors[2] = "33FF33";
$colors[3] = "66CCCC";
$colors[4] = "6666CC";
$colors[5] = "CC66CC";
$colors[6] = "996633";
$colors[7] = "006600";
$colors[8] = "333399";
$colors[9] = "C0C0C0";

# Some names for the months of the year
$monthnames[1] = "Jan";
$monthnames[2] = "Feb";
$monthnames[3] = "Mar";
$monthnames[4] = "Apr";
$monthnames[5] = "May";
$monthnames[6] = "Jun";
$monthnames[7] = "Jul";
$monthnames[8] = "Aug";
$monthnames[9] = "Sep";
$monthnames[10] = "Oct";
$monthnames[11] = "Nov";
$monthnames[12] = "Dec";

# Hoon through the CVS history
print STDERR "Reading log\n";
while(<HISTORY>){
    if(/^Working file: (.*)/){
	$filename = $1;
	print STDERR "File $filename seen\n";
	chomp $filename;
    }
    elsif(/^date: ([0-9\/]+).*author: (.*);.*state: (.*);(.*)$/){
	$date = $1;
	$author = $2;
	$state = $3;
	$comment = "";

	$_ = $4;
	if(/.*lines: \+(.*) -(.*)/){
	    $lines = int($1) + int($2);
	    if($lines > 100){
		$lines = "*";
	    }
	    else{
		$lines = ".";
	    }
	}
	elsif($revision eq "1.1"){
	    $lines = "I";
	    $revision = "";
	    }

	if($state eq "dead"){
	    $lines = "D";
	}
    }
    elsif(/^revision (.*)/){
	$revision = $1;
    }
    elsif((/^--------/) || (/^========/)){
	if(($filename eq "") || ($author eq "") || ($lines eq "") ||
	   ($date eq "") || ($comment eq "")){
	}
	else{
	    $_ = $filename;
	    if(/.*docbook.*/){
	    }
	    else{
		$date =~ s/\///g;
		$comment =~ s/\!//g;
		$comment =~ s/://g;
		
		print STDERR "Adding revision: $date, $author\n";
		$dateline{$date} = $dateline{$date} . 
		    "$filename!$author!$lines!$comment;";
		
		$date = "";
	    }
	}

	$comment = "";
    }
    else{
	s/[\r\n]/ /;
	$comment = "$comment$_";
    }
}

##############################################################################
# Draw the graph - I now do a graph per month
$newcolnum = 0;
$newauthnum = 0;
$table = "";
$prevmonth = "";
$prevyear = "";

open INDEX, "> cvsreport.html";
print INDEX "<html><head></head><body><table>";

# For each date
foreach $adate (sort keys %dateline){
    for($i = 0; $i < $newcolnum; $i++){
	$html[$i] = "";
    }

    # If this is a new month, then we need to reset ourselves and draw a 
    # new header line
    $_ = $adate;
    /([0-9][0-9][0-9][0-9])([0-9][0-9])/;
    $nowmonth = $2;
    $nowyear = $1;
    if($nowmonth ne $prevmonth){
	if($prevmonth ne ""){
	    output();
            close OUTPUT;
	    $table = "";
	}
	$loghtml = "";
	$prevmonth = $nowmonth;
	$prevyear = $nowyear;
	$newcolnum = 0;
	%cols = ();

	open OUTPUT, "> cvsreport-$nowyear$nowmonth.html";
	print OUTPUT "<html><head></head><body>\n";
    }

    @today = split(/;/, $dateline{$adate});
    foreach $event (@today){
	$_ = $event;
	/(.*)!(.*)!(.*)!(.*)/;
	$file = $1;
	$user = $2;
	$lines = $3;
	$comment = $4;
	
	if($lines eq ""){
	    $lines = "&nbsp;\n";
	}

	if($lines eq "I"){
	    $lines = "<img src=\"/cep/icon-insert.gif\" alt=\"$comment\">\n";
	}
	elsif($lines eq "D"){
	    $lines = "<img src=\"/cep/icon-delete.gif\" alt=\"$comment\">\n";
	}
	elsif($lines eq "."){
	    $lines = "<img src=\"/cep/icon-minor.gif\" alt=\"$comment\">\n";
	}
	elsif($lines eq "*"){
	    $lines = "<img src=\"/cep/icon-major.gif\" alt=\"$comment\">\n";
	}
	
	# Do we need a new cell number?
	if($cols{$file} eq ""){
	    $cols{$file} = $newcolnum;
	    $heading{$newcolnum} = $file;
	    $newcolnum++;
	}

	# Do we need a new author color?
	if($authorcolor{$user} eq ""){
	    $authorcolor{$user} = $colors[$newauthnum];
	    $authorcommits{$user} = 0;
	    $newauthnum++;
	}

	# Increment the count of commits for this author
	$authorcommits{$user}++;

	# This could be cleaned up... Build the cell
	if($html[$cols{$file}] eq "&nbsp;"){
	    $html[$cols{$file}] = "";
	}

	if($html[$cols{$file}] eq ""){
	    $html[$cols{$file}] = 
		"<tr><td bgcolor=\"$authorcolor{$user}\">$lines</td></tr>\n";
	}
	else{
	    $html[$cols{$file}] = 
		"<tr><td bgcolor=\"$authorcolor{$user}\">$lines</td></tr>" .
		    $html[$cols{$file}];
	}
    }

    # This should be improved
    for($i = 0; $i < $newcolnum; $i++){
	$html[$i] = 
	    "<td valign=\"top\"><table width=\"100%\" cellspacing=0 cellpadding=0 bgcolor=\"000000\">" 
		. $html[$i] . "</table></td>\n";
    }

    $loghtml = $loghtml . "<tr><td valign=\"top\">$adate</td>@html</tr>\n\n";
}

output();


# Finish up the index page
print INDEX "<tr><td>&nbsp;</td>";
while(($user, $color) = each %authorcolor){
    print INDEX "<td bgcolor=\"$color\">";
    print INDEX `grep $user authors | sed 's/^$user://'`;
    print INDEX "</td>"
}
print INDEX "</tr>\n";



print INDEX "</table>";
close INDEX;
close OUTPUT;







sub output(){
    if($prevmonth ne ""){
	$table = $table . "<tr><td>&nbsp;</td></tr><tr><td><b>$monthnames[$prevmonth] $nowyear</b></td>\n";
	
	# The funky header thingie
	$headerhtml = "";
	for($i = 0; $i < $newcolnum; $i++){
	    $temp = $heading{$i};
	    $temp =~ s/[\/\.]/_/g;
	    $temp =~ s/\r*\n*$//;
	    if(! -e "colheader-$temp.jpg"){
		print STDERR "Generating column header colheader-$temp.jpg\n";
		`convert -font helvetica -pointsize 10 -draw "text 1,10 $heading{$i}" -rotate -90 blank.jpg colheader-$temp.jpg`;
	    }
	    $headerhtml = $headerhtml . 
		"<td><img src=\"colheader-$temp.jpg\"></td>\n";
	}
	
	$table = $table . $headerhtml . $loghtml;
    }
    
    print INDEX "<tr><td><a href=\"cvsreport-$prevyear$prevmonth.html\">";
    print INDEX "$monthnames[$prevmonth] $prevyear</a></td>";
    while(($user, $color) = each %authorcolor){
	print INDEX "<td bgcolor=\"$color\">$authorcommits{$user}</td>";
    }
    print INDEX "</tr>\n";
    
    print OUTPUT "<table cellspacing=0 cellpadding=0>\n";
    print OUTPUT "$table</table>\n";
    print OUTPUT "<BR><HR><BR>Authors: \n";
    print OUTPUT "<table><tr>\n";
    
    print STDERR "Author summary\n";
    while(($user, $color) = each %authorcolor){
	print OUTPUT "<td bgcolor=\"$color\">$user: ";
	print STDERR "User \"$user\"\n";
	print OUTPUT `grep $user authors | sed 's/^$user://'`;
	print OUTPUT " ($authorcommits{$user})";
	$authorcommits{$user} = 0;
	print OUTPUT "</td>";
    }
    
    print OUTPUT "</tr></table>\n";
    print OUTPUT "<BR>Key: \n";
    print OUTPUT "<table><tr><td><img src=\"/cep/icon-insert.gif\">: Initial import of a file</td>\n";
    print OUTPUT "<td><img src=\"/cep/icon-delete.gif\">: File deleted from repository</td>\n";
    print OUTPUT "<td><img src=\"/cep/icon-minor.gif\">: Minor code change (less than 100 lines)</td>\n";
    print OUTPUT "<td><img src=\"/cep/icon-major.gif\">: Major code change (more than 100 lines)</td>\n";
    print OUTPUT "</tr></table>";
    
    print OUTPUT "<BR><BR>END OF REPORT\n";
    print OUTPUT "</body>\n";
}
