#!/bin/bash

files="ABOUT README ChangeLog INSTALL AUTHORS NEWS"

for item in `ls . | egrep "$1" | grep -v COPYING | grep -v Copyright | egrep -v ".sh$" | egrep -v "~$" | grep -v TODO | grep -v cvs001 | grep -v screensaver`
do
  for file in $files
  do
    if [ ! -e $item/$file ]
    then
	echo "$file $item" > $item/$file
	$EDITOR $item/$file
	cd $item
	cvs add $file
	cd ..
    fi
  done

  if [ ! -e $item/COPYING ]
  then
    cp COPYING $item/COPYING
    cd $item
    cvs add COPYING
    cd ..
  fi
done

