#!/bin/bash

count=1 

rm /home/httpd/html/news/opensource/*
export pubdate=`date "+%d %B %Y"`

for item in `find . -follow -type f -name ABOUT -print | sed -e 's/^\.\///' -e 's/\/ABOUT//' | sort -r`
do
  # If the item is not marked private
  if [ ! -e $item/PRIVATE ]
  then
    echo $item
    export project=$item
    export description=`cat $item/ABOUT`

    subst < cvstools/template > /tmp/$$
    mv /tmp/$$ /home/httpd/html/news/opensource/`printf "%06d" $count`
    count=$(( $count + 1 ))
  fi
done

export project="Summary"
export description="This is a summary of the projects on this page: <ul>"

subst < cvstools/template2 > /tmp/$$

for item in `find . -follow -type f -name ABOUT -print | sed -e 's/^\.\///' -e 's/\/ABOUT//' | sort`
do
  if [ ! -e $item/PRIVATE ]
  then
    echo "<li><a href=\"#$item\">$item</a>" >> /tmp/$$
  fi
done

mv /tmp/$$ /home/httpd/html/news/opensource/`printf "%06d" $count`
echo "$count projects published"