#!/usr/bin/perl

use strict;
use File::stat;

my($LIST, $sb, $scount, $uscount, $uncount);
$scount = 0;
$uscount = 0;

open LIST, "ls |";
while(<LIST>){
    chomp;

    if( -d $_ ){
      $uncount = 0;
#      $sb = stat($_);
#      printf "mtime %s: ", scalar localtime $sb->mtime;

      printf "%30s", $_;
      if(-e "$_/STABLE"){
	print "      stable";
	$scount++;
      }
      else{
	print "    unstable";
	$uscount++;
	$uncount++;
      }

      if(-e "$_/ABOUT"){
	print "      published";
      }
      else{
	print "    unpublished";
	$uncount++;
      }

      if(-d "/home/httpd/html/cvs/$_"){
	print "      cvsed";
      }
      else{
	print "    uncvsed";
	$uncount++;
	}

      if($uncount == 3){
	print "   ***";
      }
      print "\n";
    }
  }

print "\nSummary: stable $scount unstable $uscount\n";
