#!/bin/bash

hostname=`hostname`

for dev in `ls /dev/sd[a-z]`
do
  if [[ "$dev" =~ sd.* ]]
  then
    type="-d ata"
  else
    type=""
  fi

  echo "$hostname $dev: smartctl $type -l error $dev"
  errors=`/usr/sbin/smartctl $type -T permissive -l error $dev | grep -c "Error Count"`
  echo "$hostname $dev: $errors errors"

  if [ $errors -gt 0 ]
  then
    echo "Sent notification"
    echo "$hostname $dev: $errors" | notify mikalstill@gmail.com
  fi
done
