#!/bin/bash

timestamp=`date "+%d%m%Y-%H%M%S"`
rm -f core
prevfile="NULL"

for item in `find $1 -type f -name "*pdf"`
do
  # If we see a core file, there was an error last time
  if [ -e core ]
  then
    echo "CORE: $prevfile" >> testparse-out/$timestamp.fail
    rm -f core
  fi

  # We will parse this and see what happens
  prevfile=$item
  echo $item
  ./lexer < $item > /dev/null

  if [ $? -gt 1 ]
  then
    # This failed
    echo "$?: $item" >> testparse-out/$timestamp.fail
  elif [ -e core ]
  then
    echo "CORE: $item" >> testparse-out/$timestamp.fail
    rm -f core
  else
    echo "$?: $item" >> testparse-out/$timestamp.ok
  fi
done
