/* THIS FILE IS AUTOMATICALLY GENERATED */
char *BuildSystem= "Linux localhost.localdomain 2.4.2-2 #1 Sun Apr 8 20:41:30 EDT 2001 i686 unknown";
char *BuildDate= "Thu Feb 7 11:50:00 EST 2002";
char *BuildUser= "uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel)";
