/* jpeg.conf.h:
 *
 * Configuration file that matches the Makefile configuration file jpeg.conf
 * for building jpeg.c.  This file is automatically generated.
 */

#define HAVE_UNSIGNED_CHAR 1
#define PROTO 1
#define HAS_STDC 1
