#!/usr/local/bin/perl

use strict;
use CGI;

my($result, $path, $area, $thisslide, $maxslide, $filename, $delay);

$result = new CGI();
$path = "/home/httpd/html";
$area = $result->param('area');
$thisslide = $result->param('slide') + 1;
$maxslide = `cat $path/$area/pictures/jpegs | wc -l | tr -d " "`;

if($result->param('delay') eq ""){
    $delay = 2;
}
else{
    $delay = $result->param('delay');
}

print "Content-type: text/html\n\n";
print "<html><head><title>Slide show: $area: $thisslide</title>\n";

if($thisslide < $maxslide){
    $filename = `head -$thisslide $path/$area/pictures/jpegs | tail -1`;
    print "<meta http-equiv=\"refresh\" content=\"$delay;URL=/cgi-bin/slideshow?area=$area&slide=$thisslide&delay=$delay\">\n";
    print "</head><body><img src=\"/$area/pictures/$filename\">\n";
}
else{
    print "</head><body>End of show";
}

print "</body></html>\n";
