#!/usr/bin/perl

use strict;

while(<>){
  s/<\?xml version[^>]*>/<!DOCTYPE article PUBLIC "-\/\/OASIS\/\/DTD DocBook V4.1\/\/EN">/;
  s/<\?xml[^>]*>//;
  s/<dw-document[^>]*>//;
  s/<dw-article[^>]*>/<article>/;
  s/<\/dw-document>//;
  s/<\/dw-article>/<\/article>/;
  s/<id domino[^>]*>//;
  s/<meta[^>]*>//;
  s/<zone[^>]*>//;

  s/<seriestitle[^>]*>//;
  s/<\/seriestitle[^>]*>//;

  s/<author[^>]*>//;
  s/<\/author[^>]*>//;
  s/<bio>/<articleinfo>\n<author>\n<authorblurb>\n<para>/;
  s/<\/bio>/<\/para>\n<\/authorblurb>\n<\/author>\n<\/articleinfo/;

  s/<date[^>]*>//;
  s/<abstract[^>]*>/<abstract>\n<para>/;
  s/<\/abstract>/<\/para>\n<\/abstract>/;
  s/<column-info[^>]*>//;
  s/<docbody>//;
  s/<\/docbody>//;

  s/<todo>//g;
  s/<i>/<emphasis>/g;
  s/<\/i>/<\/emphasis>/g;
  s/<b>/<command>/g;
  s/<\/b>/<\/command>/g;

  s/<figure>//;
  s/<heading refname="" type="figure"[^>]*>.*<\/heading>//;
  s/<\/figure>//;
  s/<img src="([^"]*)"[^>]*>/<execute><cmd>img<\/cmd><args>$1<\/args><\/execute>/;

  s/<heading refname="" type="code" toc="no" name="" alttoc="">.*<\/heading>//;
  s/<code[^>]*>/<programlisting>/;
  s/<\/code>/<\/programlisting>/;

  s/<heading refname="" type="major"[^>]*>/<sect1><title>/;
  s/<heading refname="" type="minor"[^>]*>/<sect2><title>/;
  s/<heading refname="" type="sidebar"[^>]*>/<title>/;
  s/<\/heading>/<\/title>/;

  s/<p>/<para>/g;
  s/<\/p>/<\/para>/g;

  s/<ul>/<itemizedlist>/;
  s/<\/ul>/<\/itemizedlist>/;
  s/<li>/<listitem><para>/;
  s/<\/li>/<\/para><\/listitem>/;

  s/<a href[^>]*>//g;
  s/<\/a>//g;

  s/<resourcelist>/<sect1><title>Resources<\/title>/;
  s/<\/resourcelist>/<\/sect1>/;
  print $_;
}


