#!/usr/bin/python

"""Is it safe to clear this backup media?"""

# Note that this is an expensive operation

import sys
sys.path.append('/data/src/stillhq_public/trunk/python/')

import datetime
import os
import time
import MySQLdb

import gflags
import sql


FLAGS = gflags.FLAGS
gflags.DEFINE_string('dbuser', 'duplicity', 'DB username')
gflags.DEFINE_string('dbpassword', 'duplicity', 'DB user password')
gflags.DEFINE_string('dbname', 'duplicity', 'DB name')


def main(argv):
  # Parse flags
  try:
    argv = FLAGS(argv)

  except gflags.FlagsError, e:
    print 'Flags error: %s' % e
    print
    print FLAGS

  db = MySQLdb.connect(user = FLAGS.dbuser, db = FLAGS.dbname,
                       passwd = FLAGS.dbpassword)
  cursor = db.cursor(MySQLdb.cursors.DictCursor)
  cursor2 = db.cursor(MySQLdb.cursors.DictCursor)

  cursor.execute('select * from seen;')

  for row in cursor:
    cursor2.execute('insert ignore into entities(target, backup_file, '
                    'elements) values("%s", "%s", %d);'
                    %(row['target'], row['backup_file'], row['elements']))
    cursor2.execute('commit;')
    cursor2.execute('update entities set media_%s="N" where target="%s" '
                    'and backup_file="%s";'
                    %(row['media'], row['target'], row['backup_file']))
    cursor2.execute('commit;')
      

if __name__ == "__main__":
  main(sys.argv)
