#!/usr/bin/perl

use strict;

my($mode);

$mode = 0;
while(<>){
  if(($mode == 1) && (/last message repeated/)){
    print "$_";
  }
  elsif(/Calling.*-master.c/){
    print "$_";
    $mode = 1;
  }
  else{
    $mode = 0;
  }
}
