#!/bin/bash

echo "Generating data..."
make clean
make mandocs &> /tmp/out
cat /tmp/out \
 | egrep -v "^  HOSTCC" \
 | egrep -v "^  CC" \
 | egrep -v "^  MKELF" \
 | egrep -v "^  HOSTLD" \
 | egrep -v "^  DOCPROC" \
 | egrep -v "^  GEN" \
 | egrep -v "^perl.*scripts" \
 | egrep -v "^Found manpage for" \
 | egrep -v "^Processing " \
 | egrep -v "^Using " \
 | egrep -v "^Working on: " \
 | egrep -v "^Done"
