#!/bin/bash

for line in `findoccurances "$1"`
do
  file=`echo $line | sed 's/:.*//'`
  lno=`echo $line | sed 's/.*://'`

  if [ `echo $file | egrep ".c$" | wc -l | tr -d " "` -gt 0 ]
  then
    for aline in `analyze_file $file | tr " " ","`
    do
      alno=`echo $aline | sed 's/,.*//'`

      if [ $alno -lt $lno ]
      then
        hit=$aline
      elif [ $alno -gt $lno ]
      then
        echo $hit | sed -e 's/^[^,]*,//' -e 's/,/ /'
        break
      else
        echo "***BUG"
        break
      fi
    done
  else
    echo "$file not_a_c_file"
  fi
done