#!/bin/bash

# Find out what version we want
line=`wget "http://www.kernel.org/pub/linux/kernel/v2.6/testing/cset/" -O - | grep "Gzipped full patch from" | sed -e 's/<H2><A HREF="//' -e 's/">Gzipped full patch from / /' -e 's/<\/A><\/H2>//' -e 's/^ //'`
csetfilename=`echo $line | cut -f 1 -d " "`
cset=`echo $csetfilename | sed 's/.gz//'`
base=`echo $line | cut -f 2 -d " " | sed 's/^v//'`

# End early if we already have one
if [ -d linux-$base-`echo $cset | sed 's/.txt//'` ]
then
  echo "We already have the latest cset"
  exit 0
fi

# Get the cset if we need it
if [ ! -f $cset ]
then
  wget http://www.kernel.org/pub/linux/kernel/v2.6/testing/cset/$csetfilename
  gunzip $csetfilename
fi

if [ ! -f $cset ]
then
  echo "Failed to get cset"
  exit 1
fi

# Get the kernel base if we need it
if [ ! -d linux-$base ]
then
  wget http://www.kernel.org/pub/linux/kernel/v2.6/linux-$base.tar.bz2
  tar --bzip2 -xf linux-$base.tar.bz2
fi

if [ ! -d linux-$base ]
then
  echo "Failed to get the base"
  exit 2
fi

# Copy to the target directory
echo "Copying the base to the new cset directory, and applying the patch"
cp -R linux-$base linux-$base-`echo $cset | sed 's/.txt//'`
pwd=`pwd`
cd linux-$base-`echo $cset | sed 's/.txt//'`
patch -p 1 < $pwd/$cset
cd $pwd

echo linux-$base-`echo $cset | sed 's/.txt//'` > latest