#!/bin/bash

# $1: The name of the KConfig file to convert to .config
# $2: Additional targets e.g: clean dep

proctargets(){
    for target in $1
      do
      echo $target
      make $target > log.make-$target 2> err.make-$target
      if [ $? -gt 0 ]
	  then
	  echo "Make failed for $target"
	  exit
      fi
    done   
}

if [ "%$2%" != "%%" ]
then
  proctargets $2
fi

cp $1 .config

rm -f log*
rm -f err*

proctargets "dep vmlinux modules tags sgmldocs psdocs pdfdocs htmldocs bzImage"
