#!/bin/bash

# $1: pattern for patches
# $2: target kernel dir
# $3: kernel version

set -x

for item in `ls $1`
do
  echo "Building a kernel with $item"
  cd /usr/src/$2
  patch -p 1 -R < /usr/src/$item
#  mkkernel $3-$item dirty
  patch -p 1 < /usr/src/$item
done