#!/bin/bash

attempt(){
    logger mkuml `pwd`: attempting $1

    if [ "%$DISTCC_HOSTS%" == "%%" ]
    then
      jarg=""
    else
      jarg="-j 7 CC=distcc"
    fi

    make $jarg $1 ARCH=um
    die $?
}

die(){
    if [ $1 -gt 0 ]
    then
	logger mkuml `pwd`: died with exit code $1
	exit $1
    fi
}

yes "" | make config ARCH=um
attempt linux
#mount roof_fs mnt -o loop
#attempt modules_install INSTALL_MOD_PATH=`pwd`/mnt ARCH=um
#umount mnt