#!/bin/bash

set -x

# Create a new tree for kernel hacking
cp -Ral $1 $2

#cd /usr/src/$1
#for item in `find . -type d -print`
#do
#  mkdir -p /usr/src/$2/$item
#done
#
#for item in `find . -type f -print`
#do
#  ln /usr/src/$1/$item /usr/src/$2/$item
#done