#!/usr/bin/perl

# Reverse input lines based on the specified delimiter

use strict;
my($delim, @line);

if($ARGV[0] ne ""){
  $delim = $ARGV[0];
}
else{
  $delim = ": ";
}

while(<>){
  chomp;
  @line = split(/$delim/, $_);
  @line = reverse @line;
  print "@line\n";
}
