#!/usr/bin/perl

use strict;
my($FILE, $count, $mode);

$count = 0;
$mode = 0;
while(<STDIN>){
  if(/<refentry>/){
    open FILE, "> $count" or die "Couldn't open file";

#    print FILE "<!DOCTYPE refentry PUBLIC \"-//Davenport//DTD DocBook V3.0//EN\" >\n";
    print FILE "<?xml version="1.0" encoding="UTF-8"?>\n";
    print FILE "<!DOCTYPE book PUBLIC \"-//OASIS//DTD DocBook XML V4.1.2//EN\"\n";
    print FILE "    \"http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd\" []>\n";

  }

  if(/<refentryinfo>/){ $mode = 1; }

  if($mode == 0){
    print FILE $_;
  } 

  if(/<\/refentryinfo>/) { $mode = 0; }

  if(/The template for this document tried to insert/){
    close FILE;
    unlink "$count";
    open FILE, "> /tmp/$$";
  }

  if(/<\/refentry>/){
    close FILE;
    $count++;
  }
}
