#!/bin/bash

attempt(){
    logger Testcompile `pwd`: attempting $1
    make $1
    die $?
}

die(){
    if [ $1 -gt 0 ]
    then
	logger Testcompile `pwd`: died with exit code $1
	exit $1
    fi
}

logger Testcompile `pwd`: starting
attempt clean
attempt mrproper
attempt allmodconfig
attempt ""
attempt modules

attempt clean
attempt mrproper
attempt allyesconfig
attempt ""
attempt modules
logger Testcompile `pwd`: finished ok