#!/usr/local/bin/perl

use strict;
my($incomment, $origline, $code, $possfunction, $arg, %pointers, $class,
   %creates, %parents, %suppress, $temp);

$incomment = 0;
$code = "";

print STDERR "Objectify started\n";

print "// This code was automatically generated by objectify, which is\n";
print "// available from http://www.stillhq.com -- edit this file at your\n";
print "// own risk\n\n";

# Prepare the input
print STDERR "Simplifying input code\n";
while(<STDIN>){
    if((!/^#define/) && (/[ \t]*SUPPRESS\((.*)\)/)){
	$suppress{$1} = "yes";
    }
       
    # Remove comments from the line
    s/\/\/.*$//;
    s/\/\*.*\*\///;
    s/\r//g;
    s/^[ \t]+//;
    $origline = $_;
    s/\/\*.*$//;
    s/^.*\*\///;

    # We want the newlines to stay for cpp directives
    if(!/\#/){
	chomp;
    }

    if($incomment == 0){
	$code = "$code$_";
    }

    $_ = $origline;
    # Block comment closed?
    if(/.*\*\//){
	$incomment = 0;
    }

    # Comments which dangle over to the next line
    if(/\/\*.*/){
	$incomment = 1;
    }
}

$code =~ s/[ \t]+/ /g;
print STDERR "-- Simplified code ----------------------------------\n";
print STDERR $code;
print STDERR "\n-----------------------------------------------------\n";

# We now go through each line in the code, looking for functions...
print STDERR "Processing functions\n";
foreach $possfunction (split(/;/, $code)){
    $_ = $possfunction;
    my($processed, $rval, $fval, $aval);
 
    print STDERR "Possible function: $possfunction\n";

    $processed = 0;
    if(!(/INTERNAL/) && 
       (/([a-zA-Z0-9_\*]+) ([a-zA-Z0-9_\*]+) \(([^\(\)]*)\)/)){
	($rval, $fval, $aval) = ($1, $2, $3);
	$_ = $aval;
	s/ //g;
	foreach $arg (split(/,/)){
	    # If the last character is a * then this is a pointer
	    # ignore some boring pointers which are too common
	    $_ = $arg;
	    if(($arg ne "char*") && ($arg ne "int*") && ($arg ne "void*") && 
	       (/\*$/)){
		$arg =~ s/\*$//;
		print STDERR "  Pointer: $arg\n";
		$pointers{$arg} = $pointers{$arg}."$rval!$fval!$aval;";
		$processed = 1;
	    }
	}

	# If there is a * in the combination of the return value and the 
	# function name, then this is a creation function
	$_ = "$rval$fval";
	if(($rval ne "char") && ($rval ne "void") && ($rval ne "int") &&
	   (/.*\*.*/)){
	    print STDERR "  Creates: $rval\n";
	    $creates{$rval} = $creates{$rval}."$fval;";
	}
    }
    else{
	$processed = 1;
    }

    if($processed == 0){
	my($libname);
	$libname = $fval;
	$libname =~ s/_.*$//;
	$libname =~ s/\*//;
	$pointers{$libname} = $pointers{$libname}."$rval!$fval!$aval;";
    }
}

# Determine the parent relationships between classes
print STDERR "Processing classes\n";
foreach $class (keys %pointers){
    print STDERR "Class $class\n";
    if($suppress{$class} eq ""){
	# We need to output all the functions which use one of these pointers
	print STDERR "  Is not suppressed\n";
	my($rval, $fval, $aval, @argsarray);
	@argsarray = split(/;/, $pointers{$class});

	while($argsarray[0] ne ""){
	    ($rval, $fval, $aval) = split(/!/, shift @argsarray);
	    $aval =~ s/$class[ \t\*]+[, ]*//;
	    $fval =~ s/\*//;
	    
	    # We only support one parent at the moment
	    if(($parents{$rval} eq "") && ($suppress{$rval} eq "")){
		print STDERR "  Parent: $rval\n";
		$parents{$rval} = $parents{$rval}."$class";
	    }
	}
    }
}

# We need forward declarations -- we just do it for all classes
print STDERR "Generating forward declarations\n";
foreach $class (keys %pointers){
    print "class C$class;\n";
}
print "\n";


# We now know the commonly passed pointers
print STDERR "Outputing classes\n";
foreach $class (keys %pointers){
    if($suppress{$class} eq ""){
	print "class C$class\n{\n";
	print "public:\n";

	if($creates{$class} ne ""){
	    # The constructor needs to take the parent
	    print "  C$class($class *passed_ptr";
	    if(($parents{$class} ne "") && ($creates{$parents{$class}} ne "")){
		print ", $parents{$class}* passed_$parents{$class}) :\n";
		print "    m_$parents{$class}(passed_$parents{$class})\n";
		print "    { m_ptr = passed_ptr; }\n";
	    }
	    else{
		print ")\n";
		print "    { m_ptr = passed_ptr; }\n";
	    }

	    print "  ~C$class() { panda_xfree(m_ptr); }\n\n";
	}

	# We need to output all the functions which use one of these pointers
	my($rval, $fval, $aval, $origargs, @argsarray);
	@argsarray = split(/;/, $pointers{$class});

	while($argsarray[0] ne ""){
	    ($rval, $fval, $aval) = split(/!/, shift @argsarray);
	    $origargs = $aval;
	    print STDERR "  Function: $fval\n";

	    # Do we have a child relationship because of this function?
	    $aval =~ s/$class[ \t\*]+[, ]*//;
	    if($parents{$class} ne ""){
		$temp = $parents{$class};
		$aval =~ s/$temp[ \t\*]+[, ]*//;
	    }

	    # Do we have a parent relationship because of this function?
	    my($skip);
	    $skip = 0;
#	    foreach $temp (split(/[ ,]/, $aval)){
#		if($parents{$temp} eq "$class"){
#		    $skip = 1;
#		}
#	    }

	    if($skip == 0){
		print STDERR "  Not skipping\n";
		# Sometimes instead of returning a straight pointer, 
		# we will want to return a class
		$_ = $fval;
		s/[^_*]*_//;
		if($pointers{$rval} ne ""){
		    s/\*//;
		    print "  C$rval $_ (";
		}
		else{
		    print "  $rval $_ (";
		}

		my($argcount);
		$argcount = 0;
		foreach $temp (split/,/, $aval){
		    if($argcount > 0){
			print ", ";
			}
		    $temp =~ s/^ //;
		    print "$temp a$argcount";

		    # Feed in the passed args
		    $origargs =~ s/ *$temp *\**/ a$argcount/;
		    $argcount++;
		}
		
		print ") {";

		# Subst our class's pointer
		$origargs =~ s/$class *\*/m_ptr/g;

		# How about a parent pointer?
		if($parents{$class} ne ""){
		    $origargs =~ s/$parents{$class} \*/$parents{$class}/;
		    $origargs =~ s/$parents{$class}/m_$parents{$class}/;
		}

		$fval =~ s/^\*//;
		if($rval ne "void"){
		    print " return";
		}

		# If we are building a class, then do it here
		if($pointers{$rval} ne ""){
		    print " C$rval($fval($origargs)";
		    if($creates{$class} ne ""){
			print ", m_ptr";
			}
		    print "); ";
		}
		else{
		    print " $fval($origargs); ";
		}
		print "}\n";
	    }
	}
	
	if($creates{$class} ne ""){
	    print "\n";
	    print "private:\n";
	    print "  $class *m_ptr;\n";
	}

	if(($parents{$class} ne "") && ($creates{$parents{$class}} ne "")){
	    print "  $parents{$class} *m_$parents{$class};\n";
	}
	
	print "};\n\n";
    }
}
