all: verify repair zerodiv isbnmod15

verify: verify.c
	gcc verify.c -o verify

repair: repair.c
	gcc repair.c -o repair

zerodiv: zerodiv.c
	gcc zerodiv.c -o zerodiv

isbnmod15: isbnmod15.c
	gcc isbnmod15.c -o isbnmod15