foldersTree = gFld("<b>Root</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("cepConfiguration.h", "", ""))
       insDoc(aux1, gLnk("cepCore.h", "", ""))
       insDoc(aux1, gLnk("cepDataset.h", "", ""))
       insDoc(aux1, gLnk("cepDate.h", "", ""))
       insDoc(aux1, gLnk("cepDoc.h", "", ""))
       insDoc(aux1, gLnk("cepError.h", "", ""))
       insDoc(aux1, gLnk("cepErrorHandler.h", "", ""))
       insDoc(aux1, gLnk("cepLs.h", "", ""))
       insDoc(aux1, gLnk("cepMatrix.h", "", ""))
       insDoc(aux1, gLnk("cepPresentation.h", "", ""))
       insDoc(aux1, gLnk("cepTSB.h", "", ""))
       insDoc(aux1, gLnk("cepUI.h", "", ""))
       insDoc(aux1, gLnk("cepUtility.h", "", ""))
       insDoc(aux1, gLnk("cepView.h", "", ""))
       insDoc(aux1, gLnk("cepWxErrorHandler.h", "", ""))
       insDoc(aux1, gLnk("config.h", "", ""))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("cep_internal_datarow", "", "structcep__internal__datarow.html"))
       insDoc(aux1, gLnk("cepApp", "", "classcepApp.html"))
       insDoc(aux1, gLnk("cepCanvas", "", "classcepCanvas.html"))
       insDoc(aux1, gLnk("cepConfiguration", "", "classcepConfiguration.html"))
       insDoc(aux1, gLnk("cepDataset", "", "classcepDataset.html"))
       insDoc(aux1, gLnk("cepDate", "", "classcepDate.html"))
       insDoc(aux1, gLnk("cepDoc", "", "classcepDoc.html"))
       insDoc(aux1, gLnk("cepError", "", "classcepError.html"))
       insDoc(aux1, gLnk("cepErrorHandler", "", "classcepErrorHandler.html"))
       insDoc(aux1, gLnk("cepFrame", "", "classcepFrame.html"))
       insDoc(aux1, gLnk("cepLs", "", "classcepLs.html"))
       insDoc(aux1, gLnk("cepMatrix", "", "classcepMatrix.html"))
       insDoc(aux1, gLnk("cepPresentation", "", "classcepPresentation.html"))
       insDoc(aux1, gLnk("cepTSB", "", "classcepTSB.html"))
       insDoc(aux1, gLnk("cepView", "", "classcepView.html"))
       insDoc(aux1, gLnk("cepWxErrorHandler", "", "classcepWxErrorHandler.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
       insDoc(aux1, gLnk("cep_internal_datarow", "", "structcep__internal__datarow.html"))
       insDoc(aux1, gLnk("cepApp", "", "classcepApp.html"))
       insDoc(aux1, gLnk("cepCanvas", "", "classcepCanvas.html"))
       insDoc(aux1, gLnk("cepConfiguration", "", "classcepConfiguration.html"))
       insDoc(aux1, gLnk("cepDataset", "", "classcepDataset.html"))
       insDoc(aux1, gLnk("cepDate", "", "classcepDate.html"))
       insDoc(aux1, gLnk("cepDoc", "", "classcepDoc.html"))
       insDoc(aux1, gLnk("cepError", "", "classcepError.html"))
  aux2 = insFld(aux1, gFld("cepErrorHandler", "", "classcepErrorHandler.html"))
         insDoc(aux2, gLnk("cepWxErrorHandler", "", "classcepWxErrorHandler.html"))
       insDoc(aux1, gLnk("cepFrame", "", "classcepFrame.html"))
       insDoc(aux1, gLnk("cepLs", "", "classcepLs.html"))
       insDoc(aux1, gLnk("cepMatrix", "", "classcepMatrix.html"))
       insDoc(aux1, gLnk("cepPresentation", "", "classcepPresentation.html"))
       insDoc(aux1, gLnk("cepTSB", "", "classcepTSB.html"))
       insDoc(aux1, gLnk("cepView", "", "classcepView.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
