#!/usr/local/bin/perl

use strict;
my($HISTORY, $filename, $date, %dateline, $day, $adate, @dates,
   $author, %cols, $newcolnum, @today, @html, $event, $file, $user, $i,
   $table, %authorcolor, @colors, $newauthnum, %heading, $color, $temp);

open HISTORY, "< logout";

# We need some colors for authors -- I only bother to define 10 here
$colors[0] = "CC3399";
$colors[1] = "9900FF";
$colors[2] = "666699";
$colors[3] = "6699FF";
$colors[4] = "00FFCC";
$colors[5] = "66FF99";
$colors[6] = "33CC33";
$colors[7] = "99CC33";
$colors[8] = "663300";
$colors[9] = "FF6666";

# Hoon through the CVS history
while(<HISTORY>){
    if(/^Working file: (.*)/){
	$filename = $1;
	chomp $filename;
    }
    elsif(/^date: ([0-9\/]+).*author: (.*);.*;/){
	$date = $1;
	$author = $2;
	$date =~ s/\///g;
	$dateline{$date} = $dateline{$date} . "$filename!$author;";
    }
}

# Draw the graph
$newcolnum = 0;
$newauthnum = 0;
$table = "";

# For each date
@dates = sort keys %dateline;
foreach $adate (@dates) {
    for($i = 0; $i < $newcolnum; $i++){
	$html[$i] = "&nbsp;";
    }

    @today = split(/;/, $dateline{$adate});
    foreach $event (@today){
	$_ = $event;
	/(.*)!(.*)/;
	$file = $1;
	$user = $2;
	
	# Do we need a new cell number?
	if($cols{$file} eq ""){
	    $cols{$file} = $newcolnum;
	    $heading{$newcolnum} = $file;
	    $newcolnum++;
	}

	# Do we need a new author color?
	if($authorcolor{$user} eq ""){
	    $authorcolor{$user} = $colors[$newauthnum];
	    $newauthnum++;
	}

	# This could be cleaned up... Build the cell
	if($html[$cols{$file}] eq "&nbsp;"){
	    $html[$cols{$file}] = "";
	}

	if($html[$cols{$file}] eq ""){
	    $html[$cols{$file}] = 
		"<tr><td bgcolor=\"$authorcolor{$user}\">&nbsp;</td></tr>";
	}
	else{
	    $html[$cols{$file}] = $html[$cols{$file}] . 
		"<tr><td bgcolor=\"$authorcolor{$user}\">&nbsp;</td></tr>";
	}
    }

    # This should be improved
    for($i = 0; $i < $newcolnum; $i++){
	$html[$i] = "<td valign=\"top\"><table width=\"100%\" cellspacing=0 cellpadding=0>" . $html[$i] . "</table></td>";
    }

    $table = $table . "<tr><td valign=\"top\">$adate</td>@html</tr>\n";
}

# The funky header thingie
print "<table cellspacing=0 cellpadding=0><tr><td></td>";
for($i = 0; $i < $newcolnum; $i++){
    $temp = $heading{$i};
    $temp =~ s/\//_/g;
    if(! -e "colheader-$temp.jpg"){
	`convert -font helvetica -pointsize 10 -draw "text 1,10 $heading{$i}" -rotate -90 blank.jpg colheader-$temp.jpg`;
    }
    print "<td><img src=\"colheader-$temp.jpg\"></td>";
}

print "</tr>$table</table>";
print "<BR><HR><BR>Authors: ";
print "<table><tr>";

while(($user, $color) = each %authorcolor){
    print "<td bgcolor=\"$color\">$user: ";
    print `grep $user authors | sed 's/^$user://'`;
    print "</td>";
}

print "</tr></table>";
