#!/bin/bash

# This simple shell script is used to generate the command line interface.
# It was automatically generated by objectify, which is available from
# http://www.stillhq.com -- edit this file at your own risk
#
#  is a list of the files to be processed (all end in .template)
set -x

echo "" > /tmp/$$-objectify_tokens
echo "" > /tmp/$$-objectify_tokenlexs
echo "" > /tmp/$$-objectify_grammar

# panda_object class suppressed
# double class suppressed
# panda_fontmetric class suppressed
# panda class suppressed
# panda_init function suppressed
# panda_open_suppress function suppressed
# panda_imagesize function suppressed
# panda_imagesizePNG function suppressed
# panda_imagesizeJPEG function suppressed
# panda_imagesizeTIFF function suppressed
# panda_charwidth function suppressed
# panda_stringwidth function suppressed


echo "%token <textVal> PANDA_TEXTANNOTATION" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_textannotation PANDA_TEXTANNOTATION >> /tmp/$$-objectify_tokenlexs
echo -n "panda_textannotation: PANDA_TEXTANNOTATION " >> /tmp/$$-objectify_grammar
echo -n "panda_textannotation | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_textannotation(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10, \$11, \$12, \$13);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_FREETEXTANNOTATION" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_freetextannotation PANDA_FREETEXTANNOTATION >> /tmp/$$-objectify_tokenlexs
echo -n "panda_freetextannotation: PANDA_FREETEXTANNOTATION " >> /tmp/$$-objectify_grammar
echo -n "panda_freetextannotation | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_freetextannotation(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10, \$11);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_LINEANNOTATION" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_lineannotation PANDA_LINEANNOTATION >> /tmp/$$-objectify_tokenlexs
echo -n "panda_lineannotation: PANDA_LINEANNOTATION " >> /tmp/$$-objectify_grammar
echo -n "panda_lineannotation | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_lineannotation(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10, \$11, \$12, \$13, \$14, \$15);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_INSERTANNOTATION" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_insertannotation PANDA_INSERTANNOTATION >> /tmp/$$-objectify_tokenlexs
echo -n "panda_insertannotation: PANDA_INSERTANNOTATION " >> /tmp/$$-objectify_grammar
echo -n "panda_insertannotation | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo -n "m_panda_object = " >> /tmp/$$-objectify_grammar
echo "panda_insertannotation(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETLINESTART" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setlinestart PANDA_SETLINESTART >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setlinestart: PANDA_SETLINESTART " >> /tmp/$$-objectify_grammar
echo -n "panda_setlinestart | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setlinestart(m_panda_page, \$2, \$3);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_ADDLINESEGMENT" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_addlinesegment PANDA_ADDLINESEGMENT >> /tmp/$$-objectify_tokenlexs
echo -n "panda_addlinesegment: PANDA_ADDLINESEGMENT " >> /tmp/$$-objectify_grammar
echo -n "panda_addlinesegment | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_addlinesegment(m_panda_page, \$2, \$3);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_ADDCUBICCURVESEGMENT" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_addcubiccurvesegment PANDA_ADDCUBICCURVESEGMENT >> /tmp/$$-objectify_tokenlexs
echo -n "panda_addcubiccurvesegment: PANDA_ADDCUBICCURVESEGMENT " >> /tmp/$$-objectify_grammar
echo -n "panda_addcubiccurvesegment | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_addcubiccurvesegment(m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_ADDQUADRATICCURVESEGMENTONE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_addquadraticcurvesegmentone PANDA_ADDQUADRATICCURVESEGMENTONE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_addquadraticcurvesegmentone: PANDA_ADDQUADRATICCURVESEGMENTONE " >> /tmp/$$-objectify_grammar
echo -n "panda_addquadraticcurvesegmentone | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_addquadraticcurvesegmentone(m_panda_page, \$2, \$3, \$4, \$5);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_ADDQUADRATICCURVESEGMENTTWO" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_addquadraticcurvesegmenttwo PANDA_ADDQUADRATICCURVESEGMENTTWO >> /tmp/$$-objectify_tokenlexs
echo -n "panda_addquadraticcurvesegmenttwo: PANDA_ADDQUADRATICCURVESEGMENTTWO " >> /tmp/$$-objectify_grammar
echo -n "panda_addquadraticcurvesegmenttwo | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_addquadraticcurvesegmenttwo(m_panda_page, \$2, \$3, \$4, \$5);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_CLOSELINE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_closeline PANDA_CLOSELINE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_closeline: PANDA_CLOSELINE " >> /tmp/$$-objectify_grammar
echo -n "panda_closeline | " >> /tmp/$$-objectify_commands
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_closeline(m_panda_page);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_RECTANGLE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_rectangle PANDA_RECTANGLE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_rectangle: PANDA_RECTANGLE " >> /tmp/$$-objectify_grammar
echo -n "panda_rectangle | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_rectangle(m_panda_page, \$2, \$3, \$4, \$5);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_ENDLINE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_endline PANDA_ENDLINE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_endline: PANDA_ENDLINE " >> /tmp/$$-objectify_grammar
echo -n "panda_endline | " >> /tmp/$$-objectify_commands
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_endline(m_panda_page);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_STROKELINE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_strokeline PANDA_STROKELINE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_strokeline: PANDA_STROKELINE " >> /tmp/$$-objectify_grammar
echo -n "panda_strokeline | " >> /tmp/$$-objectify_commands
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_strokeline(m_panda_page);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_FILLLINE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_fillline PANDA_FILLLINE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_fillline: PANDA_FILLLINE " >> /tmp/$$-objectify_grammar
echo -n "panda_fillline | " >> /tmp/$$-objectify_commands
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_fillline(m_panda_page);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETLINEWIDTH" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setlinewidth PANDA_SETLINEWIDTH >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setlinewidth: PANDA_SETLINEWIDTH " >> /tmp/$$-objectify_grammar
echo -n "panda_setlinewidth | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setlinewidth(m_panda_page, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETLINECAP" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setlinecap PANDA_SETLINECAP >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setlinecap: PANDA_SETLINECAP " >> /tmp/$$-objectify_grammar
echo -n "panda_setlinecap | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setlinecap(m_panda_page, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETLINEJOIN" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setlinejoin PANDA_SETLINEJOIN >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setlinejoin: PANDA_SETLINEJOIN " >> /tmp/$$-objectify_grammar
echo -n "panda_setlinejoin | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setlinejoin(m_panda_page, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETLINEDASH" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setlinedash PANDA_SETLINEDASH >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setlinedash: PANDA_SETLINEDASH " >> /tmp/$$-objectify_grammar
echo -n "panda_setlinedash | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setlinedash(m_panda_page, \$2, \$3, \$4);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETFILLCOLOR" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setfillcolor PANDA_SETFILLCOLOR >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setfillcolor: PANDA_SETFILLCOLOR " >> /tmp/$$-objectify_grammar
echo -n "panda_setfillcolor | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setfillcolor(m_panda_page, \$2, \$3, \$4);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETLINECOLOR" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setlinecolor PANDA_SETLINECOLOR >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setlinecolor: PANDA_SETLINECOLOR " >> /tmp/$$-objectify_grammar
echo -n "panda_setlinecolor | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setlinecolor(m_panda_page, \$2, \$3, \$4);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_IMAGEBOX" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_imagebox PANDA_IMAGEBOX >> /tmp/$$-objectify_tokenlexs
echo -n "panda_imagebox: PANDA_IMAGEBOX " >> /tmp/$$-objectify_grammar
echo -n "panda_imagebox | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_imagebox(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_IMAGEBOXROT" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_imageboxrot PANDA_IMAGEBOXROT >> /tmp/$$-objectify_tokenlexs
echo -n "panda_imageboxrot: PANDA_IMAGEBOXROT " >> /tmp/$$-objectify_grammar
echo -n "panda_imageboxrot | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_imageboxrot(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7, \$8);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_TEXTBOX" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_textbox PANDA_TEXTBOX >> /tmp/$$-objectify_tokenlexs
echo -n "panda_textbox: PANDA_TEXTBOX " >> /tmp/$$-objectify_grammar
echo -n "panda_textbox | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_textbox(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_TEXTBOXROT" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_textboxrot PANDA_TEXTBOXROT >> /tmp/$$-objectify_tokenlexs
echo -n "panda_textboxrot: PANDA_TEXTBOXROT " >> /tmp/$$-objectify_grammar
echo -n "panda_textboxrot | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_textboxrot(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_TEXTBOXROTALIGN" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_textboxrotalign PANDA_TEXTBOXROTALIGN >> /tmp/$$-objectify_tokenlexs
echo -n "panda_textboxrotalign: PANDA_TEXTBOXROTALIGN " >> /tmp/$$-objectify_grammar
echo -n "panda_textboxrotalign | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_textboxrotalign(m_panda_pdf, m_panda_page, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_PAGEDURATION" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_pageduration PANDA_PAGEDURATION >> /tmp/$$-objectify_tokenlexs
echo -n "panda_pageduration: PANDA_PAGEDURATION " >> /tmp/$$-objectify_grammar
echo -n "panda_pageduration | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_pageduration(m_panda_pdf, m_panda_page, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_TRANSDURATION" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_transduration PANDA_TRANSDURATION >> /tmp/$$-objectify_tokenlexs
echo -n "panda_transduration: PANDA_TRANSDURATION " >> /tmp/$$-objectify_grammar
echo -n "panda_transduration | " >> /tmp/$$-objectify_commands
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_transduration(m_panda_pdf, m_panda_page, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_TRANSSTYLE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_transstyle PANDA_TRANSSTYLE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_transstyle: PANDA_TRANSSTYLE " >> /tmp/$$-objectify_grammar
echo -n "panda_transstyle | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_page" >> /tmp/$$-objectify_grammar
echo "	// Parent pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_transstyle(m_panda_pdf, m_panda_page, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar


echo "%token <textVal> PANDA_SETAUTHOR" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setauthor PANDA_SETAUTHOR >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setauthor: PANDA_SETAUTHOR " >> /tmp/$$-objectify_grammar
echo -n "panda_setauthor | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setauthor(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETCREATOR" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setcreator PANDA_SETCREATOR >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setcreator: PANDA_SETCREATOR " >> /tmp/$$-objectify_grammar
echo -n "panda_setcreator | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setcreator(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETTITLE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_settitle PANDA_SETTITLE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_settitle: PANDA_SETTITLE " >> /tmp/$$-objectify_grammar
echo -n "panda_settitle | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_settitle(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETSUBJECT" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setsubject PANDA_SETSUBJECT >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setsubject: PANDA_SETSUBJECT " >> /tmp/$$-objectify_grammar
echo -n "panda_setsubject | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setsubject(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETKEYWORDS" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setkeywords PANDA_SETKEYWORDS >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setkeywords: PANDA_SETKEYWORDS " >> /tmp/$$-objectify_grammar
echo -n "panda_setkeywords | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setkeywords(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_CREATEFONT" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_createfont PANDA_CREATEFONT >> /tmp/$$-objectify_tokenlexs
echo -n "panda_createfont: PANDA_CREATEFONT " >> /tmp/$$-objectify_grammar
echo -n "panda_createfont | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo -n "m_char = " >> /tmp/$$-objectify_grammar
echo "panda_createfont(m_panda_pdf, \$2, \$3, \$4);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETFONT" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setfont PANDA_SETFONT >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setfont: PANDA_SETFONT " >> /tmp/$$-objectify_grammar
echo -n "panda_setfont | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setfont(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETFONTSIZE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setfontsize PANDA_SETFONTSIZE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setfontsize: PANDA_SETFONTSIZE " >> /tmp/$$-objectify_grammar
echo -n "panda_setfontsize | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setfontsize(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETFONTMODE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setfontmode PANDA_SETFONTMODE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setfontmode: PANDA_SETFONTMODE " >> /tmp/$$-objectify_grammar
echo -n "panda_setfontmode | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setfontmode(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETCHARACTERSPACING" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setcharacterspacing PANDA_SETCHARACTERSPACING >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setcharacterspacing: PANDA_SETCHARACTERSPACING " >> /tmp/$$-objectify_grammar
echo -n "panda_setcharacterspacing | " >> /tmp/$$-objectify_commands
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setcharacterspacing(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETWORDSPACING" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setwordspacing PANDA_SETWORDSPACING >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setwordspacing: PANDA_SETWORDSPACING " >> /tmp/$$-objectify_grammar
echo -n "panda_setwordspacing | " >> /tmp/$$-objectify_commands
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setwordspacing(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETHORIZONTALSCALING" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_sethorizontalscaling PANDA_SETHORIZONTALSCALING >> /tmp/$$-objectify_tokenlexs
echo -n "panda_sethorizontalscaling: PANDA_SETHORIZONTALSCALING " >> /tmp/$$-objectify_grammar
echo -n "panda_sethorizontalscaling | " >> /tmp/$$-objectify_commands
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_sethorizontalscaling(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_SETLEADING" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_setleading PANDA_SETLEADING >> /tmp/$$-objectify_tokenlexs
echo -n "panda_setleading: PANDA_SETLEADING " >> /tmp/$$-objectify_grammar
echo -n "panda_setleading | " >> /tmp/$$-objectify_commands
echo -n "FLOAT " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_setleading(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_GETFONTMETRIC" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_getfontmetric PANDA_GETFONTMETRIC >> /tmp/$$-objectify_tokenlexs
echo -n "panda_getfontmetric: PANDA_GETFONTMETRIC " >> /tmp/$$-objectify_grammar
echo -n "panda_getfontmetric | " >> /tmp/$$-objectify_commands
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo -n "m_panda_fontmetric = " >> /tmp/$$-objectify_grammar
echo "panda_getfontmetric(m_panda_pdf);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_CLOSE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_close PANDA_CLOSE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_close: PANDA_CLOSE " >> /tmp/$$-objectify_grammar
echo -n "panda_close | " >> /tmp/$$-objectify_commands
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_close(m_panda_pdf);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_NEWPAGE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_newpage PANDA_NEWPAGE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_newpage: PANDA_NEWPAGE " >> /tmp/$$-objectify_grammar
echo -n "panda_newpage | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo -n "m_panda_page = " >> /tmp/$$-objectify_grammar
echo "panda_newpage(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_NEWTEMPLATE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_newtemplate PANDA_NEWTEMPLATE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_newtemplate: PANDA_NEWTEMPLATE " >> /tmp/$$-objectify_grammar
echo -n "panda_newtemplate | " >> /tmp/$$-objectify_commands
echo -n "QUOTESTR " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo -n "m_panda_page = " >> /tmp/$$-objectify_grammar
echo "panda_newtemplate(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_HIDETOOLBAR" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_hidetoolbar PANDA_HIDETOOLBAR >> /tmp/$$-objectify_tokenlexs
echo -n "panda_hidetoolbar: PANDA_HIDETOOLBAR " >> /tmp/$$-objectify_grammar
echo -n "panda_hidetoolbar | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_hidetoolbar(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_HIDEMENUBAR" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_hidemenubar PANDA_HIDEMENUBAR >> /tmp/$$-objectify_tokenlexs
echo -n "panda_hidemenubar: PANDA_HIDEMENUBAR " >> /tmp/$$-objectify_grammar
echo -n "panda_hidemenubar | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_hidemenubar(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_HIDEWINDOWUI" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_hidewindowui PANDA_HIDEWINDOWUI >> /tmp/$$-objectify_tokenlexs
echo -n "panda_hidewindowui: PANDA_HIDEWINDOWUI " >> /tmp/$$-objectify_grammar
echo -n "panda_hidewindowui | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_hidewindowui(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_FITWINDOW" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_fitwindow PANDA_FITWINDOW >> /tmp/$$-objectify_tokenlexs
echo -n "panda_fitwindow: PANDA_FITWINDOW " >> /tmp/$$-objectify_grammar
echo -n "panda_fitwindow | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_fitwindow(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_CENTERWINDOW" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_centerwindow PANDA_CENTERWINDOW >> /tmp/$$-objectify_tokenlexs
echo -n "panda_centerwindow: PANDA_CENTERWINDOW " >> /tmp/$$-objectify_grammar
echo -n "panda_centerwindow | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_centerwindow(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_NFSPAGEMODE" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_nfspagemode PANDA_NFSPAGEMODE >> /tmp/$$-objectify_tokenlexs
echo -n "panda_nfspagemode: PANDA_NFSPAGEMODE " >> /tmp/$$-objectify_grammar
echo -n "panda_nfspagemode | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_nfspagemode(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_FULLSCREEN" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_fullscreen PANDA_FULLSCREEN >> /tmp/$$-objectify_tokenlexs
echo -n "panda_fullscreen: PANDA_FULLSCREEN " >> /tmp/$$-objectify_grammar
echo -n "panda_fullscreen | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_fullscreen(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar

echo "%token <textVal> PANDA_TEXTDIRECTION" >> /tmp/$$-objectify_tokens
printf "%-30s { return %-30s; }\n" panda_textdirection PANDA_TEXTDIRECTION >> /tmp/$$-objectify_tokenlexs
echo -n "panda_textdirection: PANDA_TEXTDIRECTION " >> /tmp/$$-objectify_grammar
echo -n "panda_textdirection | " >> /tmp/$$-objectify_commands
echo -n "INTEGER " >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
echo "{" >> /tmp/$$-objectify_grammar
echo "	// Class pointer is panda_pdf" >> /tmp/$$-objectify_grammar
echo -n "	" >> /tmp/$$-objectify_grammar
echo "panda_textdirection(m_panda_pdf, \$2);" >> /tmp/$$-objectify_grammar
echo "}" >> /tmp/$$-objectify_grammar
echo "" >> /tmp/$$-objectify_grammar
# Setup the command globals
echo "  panda_fontmetric * m_panda_fontmetric;" >> /tmp/$$-objectify_pointers
echo "  char * m_char;" >> /tmp/$$-objectify_pointers
echo "  panda_page * m_panda_page;" >> /tmp/$$-objectify_pointers
echo "  panda_pdf * m_panda_pdf;" >> /tmp/$$-objectify_pointers
echo "  panda_object * m_panda_object;" >> /tmp/$$-objectify_pointers

# We also need the subst command to be sitting around ready to be used...

rm -f /tmp/$$-SuBsT
echo "#!/usr/bin/perl" >> /tmp/$$-SuBsT
echo "" >> /tmp/$$-SuBsT
echo "# \$1 is the filename header to use if not using env variables" >> /tmp/$$-SuBsT
echo "" >> /tmp/$$-SuBsT
echo "use strict;" >> /tmp/$$-SuBsT
echo "my(\$temp);" >> /tmp/$$-SuBsT
echo "" >> /tmp/$$-SuBsT
echo "while(<STDIN>){" >> /tmp/$$-SuBsT
echo "  while(/(.*)%(.+)%(.*)/){" >> /tmp/$$-SuBsT
echo "#    print STDERR \"Found: \$2, replacing with \$ENV{\$2}\n\";" >> /tmp/$$-SuBsT
echo "    if(\$ARGV[0] eq \"\"){" >> /tmp/$$-SuBsT
echo "      \$_ = \"\$1\" . \$ENV{\$2} . \"\$3\n\";" >> /tmp/$$-SuBsT
echo "    }" >> /tmp/$$-SuBsT
echo "    else{" >> /tmp/$$-SuBsT
echo "      \$temp=\`cat \$ARGV[0]-\$2\`;" >> /tmp/$$-SuBsT
echo "      chomp \$temp;" >> /tmp/$$-SuBsT
echo "      chomp \$temp;" >> /tmp/$$-SuBsT
echo "" >> /tmp/$$-SuBsT
echo "      \$_ = \"\$1\$temp\$3\n\";" >> /tmp/$$-SuBsT
echo "      }" >> /tmp/$$-SuBsT
echo "    }" >> /tmp/$$-SuBsT
echo "" >> /tmp/$$-SuBsT
echo "  print \"\$_\";" >> /tmp/$$-SuBsT
echo "  }" >> /tmp/$$-SuBsT
chmod 711 /tmp/$$-SuBsT

for file in $*
do
  outfile=`echo $file | sed 's/.template$//'`
  echo "$file -> $outfile"
  /tmp/$$-SuBsT /tmp/$$ < $file > $outfile
done

# End of file
